name: ProjectWorkspaces

options:
  bundleIdPrefix: com.projectworkspaces
  deploymentTarget:
    macOS: "15.7"

packages:
  TOMLDecoder:
    url: https://github.com/dduan/TOMLDecoder
    exactVersion: 0.4.3

targets:
  ProjectWorkspacesApp:
    type: application
    platform: macOS
    sources:
      - path: ProjectWorkspacesApp
    dependencies:
      - target: ProjectWorkspacesCore
      - package: TOMLDecoder
    settings:
      base:
        PRODUCT_NAME: ProjectWorkspaces
        PRODUCT_BUNDLE_IDENTIFIER: com.projectworkspaces.ProjectWorkspaces
        INFOPLIST_FILE: ProjectWorkspacesApp/Info.plist

  ProjectWorkspacesCore:
    type: framework.static
    platform: macOS
    sources:
      - path: ProjectWorkspacesCore
    dependencies:
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  pwctl:
    type: tool
    platform: macOS
    sources:
      - path: pwctl
    dependencies:
      - target: ProjectWorkspacesCore
      - package: TOMLDecoder

  ProjectWorkspacesCoreTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ProjectWorkspacesCoreTests
    resources:
      - path: ProjectWorkspacesCoreTests/Fixtures
    dependencies:
      - target: ProjectWorkspacesCore
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  ProjectWorkspacesAppTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ProjectWorkspacesAppTests
    dependencies:
      - target: ProjectWorkspacesApp
      - target: ProjectWorkspacesCore
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ProjectWorkspaces.app/Contents/MacOS/ProjectWorkspaces"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  ProjectWorkspaces:
    build:
      targets:
        ProjectWorkspacesApp: all
        pwctl: all
    test:
      targets:
        - ProjectWorkspacesCoreTests
        - ProjectWorkspacesAppTests
