name: AgentPanel

options:
  bundleIdPrefix: com.agentpanel
  deploymentTarget:
    macOS: "15.7"

packages:
  TOMLDecoder:
    url: https://github.com/dduan/TOMLDecoder
    exactVersion: 0.4.3

targets:
  AgentPanel:
    type: application
    platform: macOS
    sources:
      - path: AgentPanelApp
    dependencies:
      - target: AgentPanelCore
      - target: AgentPanelAppKit
    settings:
      base:
        PRODUCT_NAME: AgentPanel
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpanel.AgentPanel
        INFOPLIST_FILE: AgentPanelApp/Info.plist
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1

  AgentPanelCore:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelCore
    dependencies:
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelAppKit:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelAppKit
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelCLICore:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelCLICore
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelCLI:
    type: tool
    platform: macOS
    productName: ap
    sources:
      - path: AgentPanelCLI
    dependencies:
      - target: AgentPanelCLICore
      - target: AgentPanelCore
      - target: AgentPanelAppKit
    settings:
      base:
        PRODUCT_NAME: ap

  AgentPanelCoreTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AgentPanelCoreTests
    dependencies:
      - target: AgentPanelCore
      - target: AgentPanelAppKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  AgentPanelCLITests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AgentPanelCLITests
    dependencies:
      - target: AgentPanelCLICore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

schemes:
  AgentPanel:
    build:
      targets:
        AgentPanel: all
        AgentPanelCLI: all
        AgentPanelCoreTests: [test]
    test:
      targets:
        - AgentPanelCoreTests
        - AgentPanelCLITests
