name: AgentPanel

options:
  bundleIdPrefix: com.agentpanel
  deploymentTarget:
    macOS: "15.7"

packages:
  TOMLDecoder:
    url: https://github.com/dduan/TOMLDecoder
    exactVersion: 0.4.3

targets:
  AgentPanel:
    type: application
    platform: macOS
    sources:
      - path: AgentPanelApp
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        PRODUCT_NAME: AgentPanel
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpanel.AgentPanel
        INFOPLIST_FILE: AgentPanelApp/Info.plist

  AgentPanelCore:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelCore
    dependencies:
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelCLI:
    type: tool
    platform: macOS
    productName: ap
    sources:
      - path: AgentPanelCLI
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        PRODUCT_NAME: ap

schemes:
  AgentPanel:
    build:
      targets:
        AgentPanel: all
        AgentPanelCLI: all
