name: AgentPanel

options:
  bundleIdPrefix: com.agentpanel
  deploymentTarget:
    macOS: "15.7"

packages:
  TOMLDecoder:
    url: https://github.com/dduan/TOMLDecoder
    exactVersion: 0.4.3

targetTemplates:
  AgentPanelAppTarget:
    type: application
    platform: macOS
    sources:
      - path: AgentPanelApp
    dependencies:
      - target: AgentPanelCore
      - target: AgentPanelAppKit
      - package: TOMLDecoder
    settings:
      base:
        INFOPLIST_FILE: AgentPanelApp/Info.plist
        MARKETING_VERSION: "0.1.12"
        CURRENT_PROJECT_VERSION: 11
        CODE_SIGN_ENTITLEMENTS: release/AgentPanel.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  AgentPanel:
    templates:
      - AgentPanelAppTarget
    settings:
      base:
        PRODUCT_NAME: AgentPanel
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpanel.AgentPanel
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: Developer ID Application
          ENABLE_HARDENED_RUNTIME: YES

  AgentPanelDev:
    templates:
      - AgentPanelAppTarget
    settings:
      base:
        PRODUCT_NAME: AgentPanel Dev
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpanel.AgentPanel.dev

  AgentPanelCore:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelCore
    dependencies:
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelAppKit:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelAppKit
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelCLICore:
    type: framework.static
    platform: macOS
    sources:
      - path: AgentPanelCLICore
    dependencies:
      - target: AgentPanelCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  AgentPanelCLI:
    type: tool
    platform: macOS
    productName: ap
    sources:
      - path: AgentPanelCLI
    dependencies:
      - target: AgentPanelCLICore
      - target: AgentPanelCore
      - target: AgentPanelAppKit
      - package: TOMLDecoder
    settings:
      base:
        PRODUCT_NAME: ap
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: Developer ID Application
          ENABLE_HARDENED_RUNTIME: YES

  AgentPanelCoreTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AgentPanelCoreTests
    dependencies:
      - target: AgentPanelCore
      - target: AgentPanelAppKit
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  AgentPanelAppTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AgentPanelAppTests
    dependencies:
      - target: AgentPanel
      - target: AgentPanelCore
      - target: AgentPanelAppKit
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  AgentPanelCLITests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: AgentPanelCLITests
    dependencies:
      - target: AgentPanelCLICore
      - target: AgentPanelCore
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

schemes:
  AgentPanel:
    build:
      targets:
        AgentPanel: all
        AgentPanelCLI: all
        AgentPanelCoreTests: [test]
    test:
      targets:
        - AgentPanelCoreTests
        - AgentPanelAppTests
        - AgentPanelCLITests

  AgentPanelDev:
    build:
      targets:
        AgentPanelDev: all
