name: AgentPanel

options:
  bundleIdPrefix: com.agentpanel
  deploymentTarget:
    macOS: "15.7"

packages:
  TOMLDecoder:
    url: https://github.com/dduan/TOMLDecoder
    exactVersion: 0.4.3

targets:
  AgentPanel:
    type: application
    platform: macOS
    sources:
      - path: AgentPanelApp
    dependencies:
      - target: apcore
    settings:
      base:
        PRODUCT_NAME: AgentPanel
        PRODUCT_BUNDLE_IDENTIFIER: com.agentpanel.AgentPanel
        INFOPLIST_FILE: AgentPanelApp/Info.plist

  apcore:
    type: framework.static
    platform: macOS
    sources:
      - path: apcore
    dependencies:
      - package: TOMLDecoder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  ap:
    type: tool
    platform: macOS
    sources:
      - path: ap
    dependencies:
      - target: apcore

schemes:
  AgentPanel:
    build:
      targets:
        AgentPanel: all
        ap: all
